--[[
DEFAULT BLOCKED MODELS

THIS FILE WILL ONLY BE RUN ONCE, WHICH IS THE FIRST TIME YOU INSTALL FPP, OR AFTER THE SQLITE DATABASE IS RESET

DO NOT EDIT THIS FILE AS IT IS USELESS
GO TO Q>UTILITIES>FPP ADMIN SETTINGS > BLOCKED MODEL OPTIONS TO ADD OR REMOVE BLOCKED MODELS
--]]
FPP = FPP or {}

local defaultblocked = {
}

-- Add to SQLite database
function FPP.AddDefaultBlockedModels()
    MySQLite.begin()
    for _, v in pairs(defaultblocked) do
        FPP.BlockedModels[v] = true
        MySQLite.query("REPLACE INTO FPP_BLOCKEDMODELS1 VALUES(" .. MySQLite.SQLStr(v) .. ");")
    end
    MySQLite.commit()
end
